server: 
  port: 8090
  
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/xe?ssl=false
    username: sj
    password: sj
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true    